apiVersion: v1
kind: Service
metadata:
  name: {{ include "hbase.fullname" . }}-external
  labels:
    app.kubernetes.io/name: {{ include "hbase.name" . }}
    app.kubernetes.io/component: hbase
spec:
  type: LoadBalancer
  ports:
    - port: 2181
      name: zookeeper
    - port: 60000
      name: master-api
    - port: 16010
      name: master-web
    - port: 60020
      name: region-api
    - port: 16030
      name: region-web
  selector:
    app.kubernetes.io/name: {{ include "hbase.name" . }}
    app.kubernetes.io/component: hbase
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
