apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hbase.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hbase.name" . }}
    app.kubernetes.io/component: hbase
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hbase.name" . }}
      app.kubernetes.io/component: hbase
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  serviceName: {{ include "hbase.fullname" . }}-headless
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hbase.name" . }}
        app.kubernetes.io/component: hbase
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      containers:
        - name: hbase
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PINPOINT_VERSION
              value: 2.5.2
            - name: HBASE_VERSION
              value: 1.2.6
            - name: PINPOINT_HBASE_NAME
              value: pinpoint-hbase
            {{- if .Values.extraEnv }}
            {{ toYaml .Values.extraEnv | nindent 10 }}
            {{- end}}
          ports:
            - containerPort: 2181
              name: zookeeper
            - containerPort: 60000
              name: master-api
            - containerPort: 16010
              name: master-web
            - containerPort: 60020
              name: region-api
            - containerPort: 16030
          {{- if .Values.probes.livenessEnabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            exec:
              command:
                - ./bin/hbase hbck
          {{- end }}
          {{- if .Values.probes.readinessEnabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            exec:
              command:
                - ./bin/hbase hbck
          {{- end }}
          volumeMounts:
            - name: hbase-site
              mountPath: /opt/hbase/hbase-1.2.6/conf/hbase-site.xml
              subPath: hbase-site.xml
            - name: data
              mountPath: /home/pinpoint/hbase
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
      volumes:
        - name: hbase-site
          configMap:
            name: {{ include "hbase.fullname" . }}
      {{- if not .Values.persistence.enabled }}
        - name: data
          emptyDir: {}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - {{ .Values.persistence.hbase.accessMode | quote }}
        {{- if .Values.persistence.hbase.storageClass }}
        {{- if (eq "-" .Values.persistence.hbase.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: {{ .Values.persistence.hbase.storageClass }}
        {{- end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.hbase.size }}
  {{ end }}