# Configuration for Docker Image
image:
  repository: pinpointdocker/pinpoint-web
  tag: 2.5.2
  pullPolicy: Always

imagePullSecrets: []
securityContext: {}

nameOverride: ""
replicaCount: 2

updateStrategy:
  type: RollingUpdate
podManagementPolicy: Parallel

## Annotations to be added to Pinpoint Web pods
##
podAnnotations: {}
podSecurityContext: {}

nodeSelector: {}

## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

## Node tolerations for node-exporter scheduling to nodes with taints
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
tolerations: []
  # - key: "key"
  #   operator: "Equal|Exists"
  #   value: "value"
  #   effect: "NoSchedule|PreferNoSchedule|NoExecute(1.6 only)"

priorityClassName: ""

hostAliases: []

# Configuration for web service
service:
  type: ClusterIP
  annotations: {}
  port: 8080
  clusterPort: 9997

  external:
    enabled: true
    type: LoadBalancer
    port: 8080
    clusterPort: 9997
    annotations: {}

## persistentVolumeClaim configuration
## ref: https://kubernetes.io/docs/concepts/storage/persistent-volumes/
##
persistence:
  enabled: false
  pvcName: pinpoint-web-pvc
  accessMode: ReadWriteMany
  storageClass: ""
  size: 2Gi
  mountPath: /pinpoint-web

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 256Mi

probes:
  initialDelaySeconds: 60
  periodSeconds: 10
  endpoint: "/serverTime"
  livenessEnabled: true
  readinessEnabled: true

pinpoint:
  zookeeper:
    address: pinpoint-zookeeper

jdbc:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://pinpoint-mysql:3306/pinpoint
  username: admin
  password: admin

jvmOpts: "-Xms256M -Xmx1G -XX:+UseG1GC"

profiles: release
serverPort: 8080
adminPassword: admin

cluster:
  enable: true
  web:
    tcp:
      port: 9997

##########
# another way of setting properties.
# applied priority '.ENV' -> 'pinpoint-web.properties'
# ex) PINPOINT_ZOOKEEPER_ADDRESS overrride pinpoint.zookeeper.address
##########
extraEnv: []
#  - name: SPRING_PROFILES_ACTIVE
#    value: "release"
#  - name: WEB_SERVER_PORT
#    value: "8080"
#  - name: PINPOINT_ZOOKEEPER_ADDRESS
#    value: "pinpoint-zookeeper"
#  - name: JDBC_DRIVERCLASSNAME
#    value: "com.mysql.cj.jdbc.Driver"
#  - name: JDBC_URL
#    value: "jdbc:mysql://pinpoint-mysql:3306/pinpoint

extraProperties: |-
  config.sendUsage=false
  config.show.applicationStat=true

  cluster.enable=false
  cluster.web.tcp.port=-1

  logging.file.path=logs
  logging.level.root=INFO
  
extraContainers: []
extraVolumeMounts: []
extraVolumes: []
