apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "pinpoint-web.fullname" . }}
  labels:
    {{- include "pinpoint-web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pinpoint-web.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pinpoint-web.labels" . | nindent 8 }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      hostAliases:
        {{- toYaml .Values.hostAliases | nindent 8 }}
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
      containers:
        - name: web
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "/pinpoint/scripts/start-web.sh"]
          env:
            - name: JAVA_OPTS
              value: "{{ .Values.jvmOpts }}"
            {{- if .Values.extraEnv }}
            {{- toYaml .Values.extraEnv | nindent 12 }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ template "pinpoint-web.fullname" . }}
          ports:
            - containerPort: {{ .Values.service.port }}
            - containerPort: {{ .Values.service.clusterPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.probes.livenessEnabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            httpGet:
              path: {{ .Values.probes.endpoint }}
              port: {{ .Values.service.port }}
          {{- end }}
          {{- if .Values.probes.readinessEnabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            httpGet:
              path: {{ .Values.probes.endpoint }}
              port: {{ .Values.service.port }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /pinpoint/config
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: "{{ .Values.persistence.mountPath }}"
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}

        {{- if .Values.extraContainers }}
        {{- toYaml .Values.extraContainers | nindent 8 }}
        {{- end }}

      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: {{ template "pinpoint-web.fullname" . }}
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.pvcName }}
        {{- end }}
        {{- if .Values.extraVolumes }}
        {{- toYaml .Values.extraVolumes | nindent 8 }}
        {{- end }}
