apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pinpoint-web.fullname" . }}
  labels:
    {{- include "pinpoint-web.labels" . | nindent 4 }}
type: Opaque
data:
  ADMIN_PASSWORD: {{ .Values.adminPassword | b64enc | quote }}
  JDBC_USERNAME: {{ .Values.jdbc.username | b64enc | quote }}
  JDBC_PASSWORD: {{ .Values.jdbc.password | b64enc | quote }}