{{- if false}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "pinpoint-collector.fullname" . }}
  labels:
    {{- include "pinpoint-collector.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pinpoint-collector.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: {{ .Values.updateStrategy.type }}
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  template:
    metadata:
      labels:
        {{- include "pinpoint-collector.labels" . | nindent 8 }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      hostAliases:
        {{- toYaml .Values.hostAliases | nindent 8 }}
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
      containers:
        - name: collector
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["exec", "java", "-jar", "/pinpoint/pinpoint-collector-boot.jar"]
          args: ["--spring.config.additional-location=/pinpoint/config/pinpoint-collector.properties" ]
          env:
            - name: JAVA_OPTS
              value: "{{ .Values.jvmOpts }} "
            {{- if .Values.extraEnv }}
            {{- toYaml .Values.extraEnv | nindent 10 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ template "pinpoint-collector.fullname" . }}
            - secretRef:
                name: {{ template "pinpoint-collector.fullname" . }}
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.server.port }}
            - name: grpc-agent
              containerPort: 9991
            - name: grpc-stat
              containerPort: 9992
            - name: grpc-span
              containerPort: 9993
            - name: grpc-agent
              containerPort: 9994
            - name: grpc-agent
              containerPort: 9995
            - name: grpc-agent
              containerPort: 9996

          {{- if .Values.probes.livenessEnabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            httpGet:
              path: {{ .Values.probes.endpoint }}
              port: {{ .Values.server.port }}
          {{- end }}
          {{- if .Values.probes.readinessEnabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            httpGet:
              path: {{ .Values.probes.endpoint }}
              port: {{ .Values.service.port }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /pinpoint/config
           {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: "{{ .Values.persistence.mountPath }}"
            {{- end }}
          {{- if ne (len .Values.extraVolumeMounts) 0 }}
          {{- toYaml .Values.extraVolumeMounts | nindent 10 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      {{- if ne (len .Values.extraContainers) 0 }}
      {{- toYaml .Values.extraContainers | nindent 6 }}
      {{- end }}

      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: {{ template "pinpoint-collector.fullname" . }}-env
      {{- if ne (len .Values.extraVolumes) 0 }}
      {{- toYaml .Values.extraVolumes | indent 6 }}
      {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode | quote }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote}}
  {{- end }}
{{- end }}